In [6]:
import numpy as np
import pandas as pd

pd.set_option('display.float_format', '{:.10f}'.format)

In [7]:
df = pd.read_excel("palabras por importancia.xlsx", sheet_name="Hoja3").iloc[:,:-1]

In [8]:
df.shape

(5963, 23)

In [9]:
df.head(10)

,Palabras clave,Agropecuario,Compras,Construcción,Contaduria,Diseño,Educación,Financiero,Gastronomia,Gestión de Calidad,...,Operativo,Practicantes - Aprendices,Project Manager,Psicologia,Recursos Humanos,Salud,Servicio al cliente,SST,Talento TI,Ventas - Comercial - Administración
0,abarrotes,0.0000000000,0.0005094169,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000001138,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000
1,abastecedor,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000147377,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000
2,abastecimiento,0.0000000000,0.0103547272,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000012231,0.0000090914,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000001441,0.0000000000,0.0000000000,0.0000001211
3,abastecimientos,0.0000000000,0.0009861930,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000
4,abastesimiento,0.0000000000,0.0009861930,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000
5,abastos,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000147377,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000
6,abc,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000294755,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000
7,abierta,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0007414865,0.0000000000,...,0.0000058211,0.0000192300,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000012195,0.0000000000,0.0000000000,0.0000023046
8,abogado,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000
9,abono,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000185463

In [10]:
df.tail(10)

,Palabras clave,Agropecuario,Compras,Construcción,Contaduria,Diseño,Educación,Financiero,Gastronomia,Gestión de Calidad,...,Operativo,Practicantes - Aprendices,Project Manager,Psicologia,Recursos Humanos,Salud,Servicio al cliente,SST,Talento TI,Ventas - Comercial - Administración
5953,zonal,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0001454726,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000019039
5954,zonanorte,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000185463
5955,zonas,0.0000000000,0.0000000000,0.0008355573,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000007973,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000103134,0.0000000000,0.0000000000,0.0000000000,0.0000000000
5956,zonificador,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000147377,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000
5957,zootecnia,0.0023364490,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000
5958,zootecnista,0.0130767985,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000605719,0.0000000000,0.0000000000,0.0000000000,0.0000002060
5959,zootecnistas,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000000000,0.0001440924,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000019187
5960,zp,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000688453,0.0000000000,0.0000000000,0.0000401540
5961,zulia,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000185463
5962,zunchado,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,...,0.0000294755,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000,0.0000000000

In [11]:
columns = df.columns[1:]
columns

Index(['Agropecuario', 'Compras', 'Construcción', 'Contaduria', 'Diseño',
       'Educación', 'Financiero', 'Gastronomia', 'Gestión de Calidad',
       'Juridicos', 'Logistica', 'Marketing', 'Operativo',
       'Practicantes - Aprendices', 'Project Manager', 'Psicologia',
       'Recursos Humanos', 'Salud', 'Servicio al cliente', 'SST', 'Talento TI',
       'Ventas - Comercial - Administración'],
      dtype='object')